#lang racket/base

(require scribble/manual)
(provide sl spec-url)

(define spec-url "https://www.w3.org/TR/css-syntax-3")

(define (sl k)
  (hyperlink (format "~a#~a" spec-url (hash-ref links k k))
             (if (hash-has-key? links k)
                 (format "§~a" k)
                 k)))
(define links
  #hash(("1" . "intro")
        ("1.1" . "placement")
        ("2" . "syntax-description")
        ("2.1" . "escaping")
        ("2.2" . "error-handling")
        ("3" . "tokenizing-and-parsing")
        ("3.1" . "parsing-overview")
        ("3.2" . "input-byte-stream")
        ("3.3" . "input-preprocessing")
        ("4" . "tokenization")
        ("4.1" . "token-diagrams")
        ("4.2" . "tokenizer-definitions")
        ("4.3" . "tokenizer-algorithms")
        ("4.3.1" . "consume-token")
        ("4.3.2" . "consume-comment")
        ("4.3.3" . "consume-numeric-token")
        ("4.3.4" . "consume-ident-like-token")
        ("4.3.5" . "consume-string-token")
        ("4.3.6" . "consume-url-token")
        ("4.3.7" . "consume-escaped-code-point")
        ("4.3.8" . "starts-with-a-valid-escape")
        ("4.3.9" . "would-start-an-identifier")
        ("4.3.10" . "starts-with-a-number")
        ("4.3.11" . "consume-name")
        ("4.3.12" . "consume-number")
        ("4.3.13" . "convert-string-to-number")
        ("4.3.14" . "consume-remnants-of-bad-url")
        ("5" . "parsing")
        ("5.1" . "parser-diagrams")
        ("5.2" . "parser-definitions")
        ("5.3" . "parser-entry-points")
        ("5.3.1" . "parse-grammar")
        ("5.3.2" . "parse-stylesheet")
        ("5.3.3" . "parse-list-of-rules")
        ("5.3.4" . "parse-rule")
        ("5.3.5" . "parse-declaration")
        ("5.3.6" . "parse-list-of-declarations")
        ("5.3.7" . "parse-component-value")
        ("5.3.8" . "parse-list-of-component-values")
        ("5.3.9" . "parse-comma-separated-list-of-component-values")
        ("5.4" . "parser-algorithms")
        ("5.4.1" . "consume-list-of-rules")
        ("5.4.2" . "consume-at-rule")
        ("5.4.3" . "consume-qualified-rule")
        ("5.4.4" . "consume-list-of-declarations")
        ("5.4.5" . "consume-declaration")
        ("5.4.6" . "consume-component-value")
        ("5.4.7" . "consume-simple-block")
        ("5.4.8" . "consume-function")
        ("6" . "anb-microsyntax")
        ("6.1" . "anb-syntax")
        ("6.2" . "the-anb-type")
        ("7" . "urange")
        ("7.1" . "urange-syntax")
        ("8" . "rule-defs")
        ("8.1" . "declaration-rule-list")
        ("8.2" . "any-value")
        ("9" . "css-stylesheets")
        ("9.1" . "style-rules")
        ("9.2" . "charset-rule")
        ("10" . "serialization")
        ("10.1" . "serializing-anb")
        ("11" . "priv-sec")
        ("12" . "changes")
        ("12.1" . "changes-CR-20140220")
        ("12.2" . "changes-WD-20131105")
        ("12.3" . "changes-WD-20130919")
        ("12.4" . "changes-css21")))
