#lang racket/base

; An alphabetized list of code-point names based on the spec.

(provide (all-defined-out))

(define APOSTROPHE #\u0027)
(define ASTERISK #\u002A)
(define BACKSPACE #\u0008)
(define CARRIAGE-RETURN #\u000D)
(define CHARACTER-TABULATION #\u0009)
(define COLON #\u003A)
(define COMMA #\u002C)
(define COMMERCIAL-AT #\u0040)
(define DELETE #\u007F)
(define DIGIT-NINE #\u0039)
(define DIGIT-ZERO #\u0030)
(define EXCLAMATION-MARK-U #\u0021)
(define FORM-FEED #\u000C)
(define FULL-STOP #\u002E)
(define GREATER-THAN-SIGN #\u003E)
(define HYPHEN-MINUS #\u002D)
(define INFORMATION-SEPARATOR-ONE #\u001F)
(define LATIN-CAPITAL-LETTER-A #\u0041)
(define LATIN-CAPITAL-LETTER-E #\u0045)
(define LATIN-CAPITAL-LETTER-F #\u0046)
(define LATIN-CAPITAL-LETTER-Z #\u005A)
(define LATIN-SMALL-LETTER-A #\u0061)
(define LATIN-SMALL-LETTER-E #\u0065)
(define LATIN-SMALL-LETTER-F #\u0066)
(define LATIN-SMALL-LETTER-Z #\u007A)
(define LEFT-CURLY-BRACKET #\u007B)
(define LEFT-PARENTHESIS #\u0028)
(define LEFT-SQUARE-BRACKET #\u005B)
(define LESS-THAN-SIGN #\u003C)
(define LINE-FEED #\u000A)
(define LINE-TABULATION #\u000B)
(define LOW-LINE #\u005F)
(define NULL #\u0000)
(define NUMBER-SIGN #\u0023)
(define PERCENTAGE-SIGN #\u0025)
(define PLUS-SIGN #\u002B)
(define QUESTION-MARK #\u003F)
(define QUOTATION-MARK #\u0022)
(define REPLACEMENT-CHARACTER #\uFFFD)
(define REVERSE-SOLIDUS #\u005C)
(define RIGHT-CURLY-BRACKET #\u007D)
(define RIGHT-PARENTHESIS #\u0029)
(define RIGHT-SQUARE-BRACKET #\u005D)
(define SEMICOLON #\u003B)
(define SHIFT-OUT #\u000E)
(define SOLIDUS #\u002F)
(define SPACE #\u0020)
